In [1]:
import numpy as np

In [2]:
A = np.array([1,2,3,4])

In [3]:
print(A)

[1 2 3 4]


In [4]:
np.ndim(A)

1

In [5]:
A.shape

In [11]:
A.shape[0]

4

In [12]:
B =np.array( [[1,2],[3,4],[5,6]])

In [13]:
print(B)

[[1 2]
 [3 4]
 [5 6]]


In [14]:
np.ndim(B)

2

In [15]:
B.shape

(3, 2)

In [16]:
A1 = np.array([[1,2], [3,4]])

In [17]:
A1.shape

(2, 2)

In [18]:
B1 = np.array([[5,6], [7,8]])

In [19]:
B1.shape

(2, 2)

In [20]:
np.dot(A1,B1)

array([[19, 22],
       [43, 50]])

In [21]:
A2 = np.array([[1,2,3], [4,5,6]])

In [22]:
B2 = np.array([[1,2], [3,4], [5,6]])

In [23]:
np.dot(A2, B2)

array([[22, 28],
       [49, 64]])